name: CI

on:
  pull_request:
  push: { branches: [ main ] }

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pipx install poetry
      - name: Install deps
        run: poetry install --no-interaction --no-ansi
      - name: Run tests
        run: poetry run pytest
