site_name: delta-engine
nav:
  - Home: index.md
  - Architecture: architecture.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - javascripts/mermaid.js
